### ISSUE TITLE
Proposal: Merge efforts in some way

### ISSUE THREAD

**Issue by mehcode** [softprops/envy#13]
Definitely like what you have here.

@softprops I've been working on a very general configuration solution that has become a superset of this crate's functionality. I'm proposing using [`config`](https://github.com/mehcode/config-rs) internally in `envy`. 

For an example, here is the example from the readme converted to use `config`.

```rust
#[macro_use]
extern crate serde_derive;
extern crate config;

#[derive(Deserialize, Debug)]
struct Config {
  foo: u16,
  bar: bool,
  baz: String,
  boom: Option<u64>
}

fn main() {
    let mut c = config::Config::new();

    // Not possible to error in this case but the `merge` function is very generic
    c.merge(config::Environment::new()).unwrap();

    match c.try_into::<Config>() {
       Ok(config) => println!("{:#?}", config),
       Err(error) => panic!("{:#?}", error)
    }
}
```

A couple things you'd gain from using `config` under-the-hood of `envy`:
 - Prefix ( would fix https://github.com/softprops/envy/issues/12 ) with `config::Environment::with_prefix("SOME_APP")`
 - Better Errors, omitting a required key looks like (in the example):
    ```
    thread 'main' panicked at 'missing field `baz`', src/main.rs:21:21
    ```

**Comment by softprops** [comment]
Very cool. Thanks for reaching out!

We use envy heavily where I work to solve a very straightforward problem. We run our rust apps in containers inside kubernetes which generally leads you towards 12 factor (env var) oriented configuration. The problem we had was onerous type conversions from strings on app startup in all of our rust apps. We've had really really good experience with serde for solving that problem for json by making it easy to go from strings to typed values so an env + serde solution was a natural fit for the problem at hand. That's where this crate came from. No more, no less. 

For our older jvm apps we had at one time looked into a netflix [config management lib](https://github.com/Netflix/archaius/blob/master/README.md) to wrangle our configuration issues. What we learned was that it ended out indirectly promoting nonuseful complexity in making configuration more interesting (and complicated) than it needed to be by allowing for different configuration patterns to be overlayed and composed. It allows enginners to mix and match styles between apps which  only continued to create inconsistency. Netflixes lib is there to make it appear that there's a useful consistent interface to an inconsistency problem. After working through that problem we realized that configuration should be less interesting and more focused on patterns that are actually needed. The important part is the app not how its configured! We ended up solving our consistency problem another way, using a consistent format. In our case 12 factor worked well enough to not need other formats.

I think that configuration management libs like nexflixes and yours definitely have their place in more complicated sets of applications but I don't really work with those kinds of apps anymore :) i dont feel like moving own apps over to config would get us much more value and could potentially let's backside into allowing for config complexity.

The prefix gh issue has been left open because I'm kind of on the fense for where that functionality actually belongs. Serde already has the ability to alias field names to match the shape of its data format. Prefixing fields is really in line with that functionality. I've held off on adding that to envy because I really belongs as a feature in serde attributes. 

Error messages are definitely sub optimal in envy but its less often a problem than is worth the time I think it would take to change that. In general I start up an app wrong once and right the other 99% times after. Time spent on 1% problem hasnt been super motivating. I mainly focus my energy where there's higher impact! That said think better error messages wouldn't be that hard to add with serde hooks

All that said, I'd be happy to promote your lib in envys readme for cases where envy may fall short in complex configuration setups. For my own apps, I want to keep configuration boring so I an focus on the important parts!

**Comment by mehcode** [comment]
Oh. I think you're misunderstanding me. Thanks for taking the time to respond. I agree with most of what you said.

`config` is not meant to be used by everybody _directly_. Because the library is very generic (it does nothing by default) it's actually meant to be wrapped up in little libs that _are_ opinionated (like this one).

I think a pure 12-factor approach is very good. Of course, not everyone agrees with that. Some like files, etcd, etc. One of the key goals of `config` is for a developer to wrap up their model for configuration in a tiny lib that accelerates their workflow.

For instance, someone could write a config library that mirrors https://github.com/lorenwest/node-config using `config` as a base (instead of rolling their own merging code). `config` has a set of common code (like conversions) and is shared with other librarys (like `envy`). We can all collaborate on that _generic_ code together.

---

With my proposal, `envy` would become (something like):

```rust
extern crate config;

pub fn from_env<'de, T: Deserialize<'de>>() -> config::Result<T> {
    let mut c = config::Config::new();
    c.merge(config::Environment::new())?;

    T::deserialize(c)
}
```

The idea is the users of the this library won't realize the change. Furthermore I'd add you as a collaborator to `config` and you could help maintain the pieces of the common code `envy` is relying on (mainly type conversions and deserialization).

**Comment by softprops** [comment]
Ok. Let me dig into this a bit more this weekend. 

From the outset envy is nothing more than a serde deserializer for iterables of tuples of strings. In that sense it could be an provider for config internals for environment or similar types. Similar to a yaml-rs for yaml, serde json for json, or serde toml for toml. Envy is just a deserializer for env vars.

For me, serde _is_ the common _generic_ interface for deserializing into typed structs. 

I think you may be right and I may be caught in a misunderstanding. I'll take a closer look this weekend. I do agree a sharable deserializer could be ideal. Upgrading from serde 0.9 to 1.0 was... unpleasant ( though I have to give it's maintainers props for the helpful migration tips ). I wouldn't mind sharing that kind of migration "fun" the next time serde makes breaking changes like that :)
